# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: gotiac
resources:
  gotiac:index:StaticPage:
    isComponent: true
    inputProperties:
      indexContent:
        type: string
        description: The HTML content for index.html.
    requiredInputs:
      - indexContent
    properties:
      bucket:
        "$ref": "/aws/v4.0.0/schema.json#/resources/aws:s3%2Fbucket:Bucket"
        description: The bucket resource.
      websiteUrl:
        type: string
        description: The website URL.
    required:
      - bucket
      - websiteUrl
  gotiac:index:FileHosting:
    isComponent: true
    inputProperties:
      domain:
        type: string
        description: The file hosting domain.
      # hostedZoneId:
      #   type: string
      #   description: The hosted zone ID.
    requiredInputs:
      - domain
      # - hostedZoneId
    properties:
      url:
        type: string
        description: The file hosting URL.
      privateKeyParameterName:
        type: string
        description: The parameter name for the private key.
      privateKeyId:
        type: string
        description: The ID the private key.
    required:
      - url
      - privateKeyParameterName
      - privateKeyId
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
      Pulumi.Aws: 4.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/pulumi/pulumi-gotiac/sdk/go/gotiac
  nodejs:
    dependencies:
      "@pulumi/aws": "^6.0.0"
    devDependencies:
      typescript: "*"
  python:
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-aws: ">=4.0.0,<5.0.0"
