# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .file_hosting import *
from .provider import *
from .static_page import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "gotiac",
  "mod": "index",
  "fqn": "pulumi_gotiac",
  "classes": {
   "gotiac:index:FileHosting": "FileHosting",
   "gotiac:index:StaticPage": "StaticPage"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "gotiac",
  "token": "pulumi:providers:gotiac",
  "fqn": "pulumi_gotiac",
  "class": "Provider"
 }
]
"""
)
