# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['FileHostingArgs', 'FileHosting']

@pulumi.input_type
class FileHostingArgs:
    def __init__(__self__, *,
                 domain: pulumi.Input[str],
                 bucket_name: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a FileHosting resource.
        :param pulumi.Input[str] domain: The file hosting domain.
        :param pulumi.Input[str] bucket_name: The name of an existing s3 Bucket to link as origin. If not provided, a new bucket will be created.
        """
        pulumi.set(__self__, "domain", domain)
        if bucket_name is not None:
            pulumi.set(__self__, "bucket_name", bucket_name)

    @property
    @pulumi.getter
    def domain(self) -> pulumi.Input[str]:
        """
        The file hosting domain.
        """
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: pulumi.Input[str]):
        pulumi.set(self, "domain", value)

    @property
    @pulumi.getter(name="bucketName")
    def bucket_name(self) -> Optional[pulumi.Input[str]]:
        """
        The name of an existing s3 Bucket to link as origin. If not provided, a new bucket will be created.
        """
        return pulumi.get(self, "bucket_name")

    @bucket_name.setter
    def bucket_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "bucket_name", value)


class FileHosting(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 bucket_name: Optional[pulumi.Input[str]] = None,
                 domain: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a FileHosting resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] bucket_name: The name of an existing s3 Bucket to link as origin. If not provided, a new bucket will be created.
        :param pulumi.Input[str] domain: The file hosting domain.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: FileHostingArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a FileHosting resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param FileHostingArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(FileHostingArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 bucket_name: Optional[pulumi.Input[str]] = None,
                 domain: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = FileHostingArgs.__new__(FileHostingArgs)

            __props__.__dict__["bucket_name"] = bucket_name
            if domain is None and not opts.urn:
                raise TypeError("Missing required property 'domain'")
            __props__.__dict__["domain"] = domain
            __props__.__dict__["private_key_id"] = None
            __props__.__dict__["private_key_parameter_name"] = None
            __props__.__dict__["url"] = None
        super(FileHosting, __self__).__init__(
            'gotiac:index:FileHosting',
            resource_name,
            __props__,
            opts,
            remote=True)

    @property
    @pulumi.getter(name="privateKeyId")
    def private_key_id(self) -> pulumi.Output[str]:
        """
        The ID the private key.
        """
        return pulumi.get(self, "private_key_id")

    @property
    @pulumi.getter(name="privateKeyParameterName")
    def private_key_parameter_name(self) -> pulumi.Output[str]:
        """
        The parameter name for the private key.
        """
        return pulumi.get(self, "private_key_parameter_name")

    @property
    @pulumi.getter
    def url(self) -> pulumi.Output[str]:
        """
        The file hosting URL.
        """
        return pulumi.get(self, "url")

